version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/go-mod
    environment:
      - GOPROXY=https://goproxy.cn,direct  # 如果在中国，可以使用国内代理
    working_dir: /app
    command: go run main.go
    restart: unless-stopped
